"""
Migration script: Imports dev data from pg_dump SQL file into the production DATABASE_URL.
Used during production build to seed the production database with data.

The SQL dump file (dev_data_dump.sql) is generated by running export_dev_data.py
before deploying. The pg_dump uses --schema=backend_vnext --clean --if-exists,
so it only drops/recreates tables within that schema, not the entire database.
"""
import os
import sys
import subprocess

TARGET_DB_URL = os.environ.get("DATABASE_URL")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DUMP_FILE = os.path.join(SCRIPT_DIR, "dev_data_dump.sql")

if not TARGET_DB_URL:
    print("WARNING: DATABASE_URL not set, skipping data migration")
    sys.exit(0)

if not os.path.exists(DUMP_FILE):
    print(f"WARNING: SQL dump file not found at {DUMP_FILE}, skipping data migration")
    print("Run 'python scripts/export_dev_data.py' first to generate the dump.")
    sys.exit(0)

file_size = os.path.getsize(DUMP_FILE)
if file_size < 100:
    print(f"WARNING: SQL dump file is too small ({file_size} bytes), skipping")
    sys.exit(0)

print(f"Importing data from: {DUMP_FILE} ({file_size / 1024:.1f} KB)")
print(f"Target DB: {TARGET_DB_URL[:60]}...")
print()

result = subprocess.run(
    [
        "psql",
        TARGET_DB_URL,
        "--single-transaction",
        "-f", DUMP_FILE,
    ],
    capture_output=True,
    text=True,
)

stdout_tail = result.stdout[-3000:] if len(result.stdout) > 3000 else result.stdout
stderr_tail = result.stderr[-3000:] if len(result.stderr) > 3000 else result.stderr

has_errors = "ERROR" in result.stderr

if result.returncode != 0 or has_errors:
    print(f"psql stdout (last 3000 chars):\n{stdout_tail}")
    print(f"\npsql stderr (last 3000 chars):\n{stderr_tail}")
    if has_errors:
        print("\nERROR: psql import encountered errors. Build will fail.")
        sys.exit(1)

print("psql import completed successfully.")

try:
    import psycopg2
    conn = psycopg2.connect(TARGET_DB_URL)
    cur = conn.cursor()

    cur.execute("""
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'backend_vnext' AND table_type = 'BASE TABLE'
        ORDER BY table_name
    """)
    tables = [r[0] for r in cur.fetchall()]

    print(f"\n--- Verification ({len(tables)} tables) ---")
    total_rows = 0
    for table in tables:
        cur.execute(f'SELECT COUNT(*) FROM backend_vnext."{table}"')
        count = cur.fetchone()[0]
        total_rows += count
        print(f"  {table}: {count} rows")

    print(f"\nTotal: {total_rows} rows across {len(tables)} tables")

    if total_rows == 0 and len(tables) > 0:
        print("WARNING: All tables are empty after import!")

    conn.close()
except Exception as e:
    print(f"Verification step failed: {e}")
    print("Import may have succeeded but verification could not connect.")

print("Data migration complete!")
